<h4> Performance of NumPy vs. Built-in Python object </h4>

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(my_arr)

numpy_per = %time for _ in range(10): my_arr2= my_arr * 2
numpy_per

CPU times: user 20.9 ms, sys: 15.9 ms, total: 36.8 ms
Wall time: 46.8 ms


In [11]:
builtin_per = %time for _ in range(10): my_list2 = [x*2 for x in my_list]
builtin_per

CPU times: user 2.7 s, sys: 117 ms, total: 2.82 s
Wall time: 2.84 s


<h4>Working with nested sequence of list in NumPy</h4>

In [21]:
data = [[1,2,3], [4,5,6]]

arr = np.array(data)
arr.shape
arr.ndim
arr

array([[1, 2, 3],
       [4, 5, 6]])

<h4> Boolean Indexing </h4>

In [32]:
num = np.random.randn(7,4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# It will set all the negative values in ndarray to 0
#num[num<0] = 0
cond = names == 'Bob'
print(num)

# To invert to result
num[~cond]

# Unary Operator
mask = (names == 'Bob') | (names == 'Joe')

num[names != 'Joe'] = 8
num[mask]

[[ 1.43557627 -1.09817543  0.44046755  0.80495663]
 [ 1.27697874  0.34878352 -0.71136721 -0.01593855]
 [-0.30354192 -0.4135478   1.99067563 -1.48751501]
 [ 0.79042721  0.84611955  0.5685947  -2.33133782]
 [-0.24870595  0.57038387 -0.91614404 -3.14150912]
 [-0.03208382 -0.09524793 -0.24864763  0.23836339]
 [ 0.43595555  0.57279476 -0.59901348  0.19222599]]


array([[ 8.        ,  8.        ,  8.        ,  8.        ],
       [ 1.27697874,  0.34878352, -0.71136721, -0.01593855],
       [ 8.        ,  8.        ,  8.        ,  8.        ],
       [-0.03208382, -0.09524793, -0.24864763,  0.23836339],
       [ 0.43595555,  0.57279476, -0.59901348,  0.19222599]])

<h4> Fancy Indexing </h4>

In [10]:
arr = np.empty((8,3))
arr

for i in range(8):
    arr[i]=i
print(arr[[4,7,2]])

print("\nWe can use negative sign to select the values from the end")
print(arr[[-5, -2]])

[[4. 4. 4.]
 [7. 7. 7.]
 [2. 2. 2.]]

We can use negative sign to select the values from the end
[[3. 3. 3.]
 [6. 6. 6.]]


In [14]:
arr1 = np.arange(32).reshape((8,4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])