<h4> Performance of NumPy vs. Built-in Python object </h4>

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(my_arr)

numpy_per = %time for _ in range(10): my_arr2= my_arr * 2
numpy_per

CPU times: user 20.9 ms, sys: 15.9 ms, total: 36.8 ms
Wall time: 46.8 ms


In [11]:
builtin_per = %time for _ in range(10): my_list2 = [x*2 for x in my_list]
builtin_per

CPU times: user 2.7 s, sys: 117 ms, total: 2.82 s
Wall time: 2.84 s


<h4>Working with nested sequence of list in NumPy</h4>

In [21]:
data = [[1,2,3], [4,5,6]]

arr = np.array(data)
arr.shape
arr.ndim
arr

array([[1, 2, 3],
       [4, 5, 6]])

<h4> Boolean Indexing </h4>

In [32]:
num = np.random.randn(7,4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# It will set all the negative values in ndarray to 0
#num[num<0] = 0
cond = names == 'Bob'
print(num)

# To invert to result
num[~cond]

# Unary Operator
mask = (names == 'Bob') | (names == 'Joe')

num[names != 'Joe'] = 8
num[mask]

[[ 1.43557627 -1.09817543  0.44046755  0.80495663]
 [ 1.27697874  0.34878352 -0.71136721 -0.01593855]
 [-0.30354192 -0.4135478   1.99067563 -1.48751501]
 [ 0.79042721  0.84611955  0.5685947  -2.33133782]
 [-0.24870595  0.57038387 -0.91614404 -3.14150912]
 [-0.03208382 -0.09524793 -0.24864763  0.23836339]
 [ 0.43595555  0.57279476 -0.59901348  0.19222599]]


array([[ 8.        ,  8.        ,  8.        ,  8.        ],
       [ 1.27697874,  0.34878352, -0.71136721, -0.01593855],
       [ 8.        ,  8.        ,  8.        ,  8.        ],
       [-0.03208382, -0.09524793, -0.24864763,  0.23836339],
       [ 0.43595555,  0.57279476, -0.59901348,  0.19222599]])

<h4> Fancy Indexing </h4>

In [10]:
arr = np.empty((8,3))
arr

for i in range(8):
    arr[i]=i
print(arr[[4,7,2]])

print("\nWe can use negative sign to select the values from the end")
print(arr[[-5, -2]])

[[4. 4. 4.]
 [7. 7. 7.]
 [2. 2. 2.]]

We can use negative sign to select the values from the end
[[3. 3. 3.]
 [6. 6. 6.]]


In [14]:
arr1 = np.arange(32).reshape((8,4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

<h4>Transposing Arrays and Swaping Axes</h4>

In [20]:
# Transposing an array
arr2 = np.arange(20).reshape((4, 5))
print(arr2)
arr2.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [22]:
# Inner matrix product using np.dot
arr = np.random.randn(10,3)
np.dot(arr.T, arr)

array([[11.43864653, -1.88187474,  2.90269789],
       [-1.88187474, 14.87775377, -5.62815732],
       [ 2.90269789, -5.62815732, 11.39099877]])

In [33]:
# For higher dimensional array
arr = np.random.randn(16).reshape((2,2,4))
print(arr)
arr.transpose(1,0,2)


[[[-0.63902513  2.63208294  0.48069398 -0.64363022]
  [-0.74302885 -0.24514618 -0.85241461  0.4275599 ]]

 [[ 0.10219083 -0.87848456  0.1226736  -0.64609349]
  [ 1.64780944 -1.03021741 -1.53191546 -1.1339234 ]]]


array([[[-0.63902513,  2.63208294,  0.48069398, -0.64363022],
        [ 0.10219083, -0.87848456,  0.1226736 , -0.64609349]],

       [[-0.74302885, -0.24514618, -0.85241461,  0.4275599 ],
        [ 1.64780944, -1.03021741, -1.53191546, -1.1339234 ]]])

In [39]:
# Swap-axes takes the pair of axis numbers
# and switches the indicated axes to rearrange the data

arr = np.arange(16).reshape((2, 2, 4))
arr.swapaxes(1,2)

# swapaxes similarly returns a view on the data without making a copy.

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

<h4>Universal Functions: Fast Element-Wise Array Function</h4>

In [48]:
# Unary ufunc
arr = np.arange(1,11)

print(np.sqrt(arr))
print(np.exp(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [50]:
# Binary ufunc (Maximum)

x = np.random.randn(10)
y = np.random.randn(10)
print("The value of x elements", x)
print("The value of y elements", y)

np.maximum(x,y)
# Here numpy maximum function computes the max value element-wise

The value of x elements [-0.72375818  0.63286571  2.26093517 -0.2628575  -0.78491155 -1.10593942
 -0.69467613 -0.20607559 -0.52981597 -0.07035485]
The value of y elements [-0.83429357 -1.19671843 -2.01060604  1.02798321  1.10236365  0.4850084
 -2.39899958 -0.62644993 -0.09813163 -0.22718964]


array([-0.72375818,  0.63286571,  2.26093517,  1.02798321,  1.10236365,
        0.4850084 , -0.69467613, -0.20607559, -0.09813163, -0.07035485])

In [55]:
# An ufunc can return multiple arrays

arr = np.random.randn(10) * 6
print(arr)

remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[ -6.66101932   4.7140446   -6.08732872  -0.89417874  -0.19228552
  -7.51839315   8.58062863   3.26084794   6.13795457 -12.02854266]
[-0.66101932  0.7140446  -0.08732872 -0.89417874 -0.19228552 -0.51839315
  0.58062863  0.26084794  0.13795457 -0.02854266]
[ -6.   4.  -6.  -0.  -0.  -7.   8.   3.   6. -12.]


In [59]:
np.sqrt(arr, arr)
arr

array([       nan, 1.47349417,        nan,        nan,        nan,
              nan, 1.71151132, 1.34379381, 1.57400431,        nan])

<center><h4> Unary Functions Table </h4></center>
<img src="image/1.png">

In [ ]:
<center