<h4> Performance of NumPy vs. Built-in Python object </h4>

In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(my_arr)

numpy_per = %time for _ in range(10): my_arr2= my_arr * 2
numpy_per

CPU times: user 27.9 ms, sys: 12 ms, total: 39.9 ms
Wall time: 46 ms


In [11]:
builtin_per = %time for _ in range(10): my_list2 = [x*2 for x in my_list]
builtin_per

CPU times: user 2.7 s, sys: 117 ms, total: 2.82 s
Wall time: 2.84 s


<h4>Working with nested sequence of list in NumPy</h4>

In [21]:
data = [[1,2,3], [4,5,6]]

arr = np.array(data)
arr.shape
arr.ndim
arr

array([[1, 2, 3],
       [4, 5, 6]])

<h4> Boolean Indexing </h4>

In [28]:
num = np.random.randn(7,4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# It will set all the negative values in ndarray to 0
#num[num<0] = 0
cond = names == 'Bob'
print(num)

# To invert to result
num[~cond]
mask = (names == 'Bob') | (names == 'Joe')
num[mask]


[[-0.28471886  0.33824448  1.09632199 -1.18886331]
 [-0.68002506 -1.1751691  -1.35315816  0.85543846]
 [-0.6097765   0.07136144 -0.78144932  1.10607427]
 [ 1.07209761  0.55628288 -1.63269828  1.06017611]
 [ 0.09621653 -1.87772298 -1.56014794 -1.89692166]
 [-1.23523306  2.39503674  1.08830373 -0.15300371]
 [ 1.71788219 -1.95497526 -1.0294092   1.25858656]]


array([[-0.6097765 ,  0.07136144, -0.78144932,  1.10607427],
       [ 0.09621653, -1.87772298, -1.56014794, -1.89692166]])